version: "2"
services:
  go:
    image: gcr.io/ntopus-1379/timed-event:0.3.1.156719501
    command: ["-c=./config/config.json"]
    networks:
      - back
    expose:
      - "9010"
    ports:
      - "9010:9010"
    volumes:
      - ./bin/config:/app/config
    depends_on:
      - arango
      - rabbitmq
    restart: on-failure
  arango:
    image: arangodb:3.4.7
    ports:
      - "8529:8529"
    networks:
      back:
        aliases:
          - "timedEvent.db.ivanmeca.com.br"
    volumes:
      - ./docker-data/arangodb:/var/lib/arangodb
    environment:
      ARANGO_ROOT_PASSWORD: "rootpass"
      ARANGO_STORAGE_ENGINE: rocksdb
  rabbitmq:
    image: rabbitmq:management
    networks:
      back:
        aliases:
          - "timedEvent.queue"
    expose:
      - "15672"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: randomUser
      RABBITMQ_DEFAULT_PASS: randomPass
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - ./docker-data/rabbitmq/data:/var/lib/rabbitmq

networks:
  back: